### ISSUE TITLE
关于action一处的一点问题

### ISSUE THREAD

**Issue by AnhuiWdan** [superman66/vue2.x-douban#13]
```
[types.CLEAN_MOVIE](context){
    context.commit(types.CLEAN_MOVIE);
  },
```
在action的方法里有这样的一句，但是后面的commit()没有使用`[types.CLEAN_MOVIE]`，是否是遗忘或者有其他原因，还请告知

**Comment by superman66** [comment]
在开发 store 的时候想着可能会需要清除单个 movie 对象的需求，但是后续开发中发现并没有用到。所有就导致定义了，但是没有发生调用。
