### ISSUE TITLE
请问能否增强一下搜索功能呢？

### ISSUE THREAD

**Issue by kukudemajia** [superman66/vue2.x-douban#14]
比如我要搜索2012年以后上映、评分在8.0以上的电影
增加组合筛选功能，貌似一直没有找到合适的

**Comment by superman66** [comment]
豆瓣api并没有提供对应这么多查询参数的接口。
如果你想做的话，得自己去抓包查看真实的 api，然后代理去访问才能行。

**Comment by kukudemajia** [comment]
呃，恕我无知啊，我以为可以直接实现呢
