### ISSUE TITLE
为什么图片加载有问题

### ISSUE THREAD

**Issue by StephenWu5** [superman66/vue2.x-douban#17]
Welcome to the vue2.x-douban wiki!

为什么我本地跑起来是这么样子,有的图片请求不到,有的图片请求得到!!

![666](https://raw.githubusercontent.com/StephenWu5/StephenWu5.github.io/master/images/image.png)

能告诉我什么原因吗???

**Comment by superman66** [comment]
这是豆瓣 api 防盗链机制。所以导致访问图片会返回 403 http code。
你可以将 api 地址改为 https://github.com/superman66/vue2.x-douban/blob/master/src/store/api.js#L7
改成线上的 API 再试试 
```
// 使用代理
const HOST = 'https://node-douban-api.herokuapp.com';
```

**Comment by StephenWu5** [comment]
ok,thanks...

**Comment by StephenWu5** [comment]
https://node-douban-api.herokuapp.com 这个服务器是哪位老大搭的?you?

**Comment by superman66** [comment]
恩，我自己搭在 herokuapp 上的。

**Comment by StephenWu5** [comment]
好的
