### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by lemongeek** [superman66/vue2.x-douban#2]
@ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v
-74521568!./~/sass-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/co
mponents/Spinner.vue 4:14-264 13:2-17:4 14:20-270
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  1.47 MB       0
webpack: Failed to compile.

 重新安装npm install node-sass 还是出错

**Comment by lemongeek** [comment]
ERROR in Cannot find module 'node-sass'
@ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v
-74521568!./~/sass-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/co
mponents/Spinner.vue 4:14-264 13:2-17:4 14:20-270
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  1.47 MB       0
webpack: Failed to compile.

**Comment by superman66** [comment]
这是你的node-sass没装成功。
node-sass由于被墙，很经常装不上。你翻个墙或者切换成淘宝registry。

**Comment by Brass-neck** [comment]
使用cnpm i node-sass
