### ISSUE TITLE
 Cannot find module 'semver'

### ISSUE THREAD

**Issue by uneverno** [superman66/vue2.x-douban#4]
![7 d3x 13c hhx 4dtj1w7](https://cloud.githubusercontent.com/assets/22190956/23242143/3ce57196-f9b2-11e6-94d5-5866be834852.png)

我运行的时候总是如上报错，请问我该怎么解决这个问题了？运行环境为node+npm .谢谢

**Comment by superman66** [comment]
1. 首先确认下`npm install`的时候，是否所有的东西都正确装完了
2. `Cannot find module 'semver'`，那就把这个module再安装一遍.
```bash
npm install semver
```
3. 如果还是不行，那你就项目删掉，重新clone，重新执行`npm install`再安装一遍。
