### ISSUE TITLE
运行npm run dev报错

### ISSUE THREAD

**Issue by deepred5** [superman66/vue2.x-douban#7]
```
ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-18ded60a!./~/vue-loader/lib/selector.js?type=template&index=0!./src/components/header.vue

  Vue template syntax error:

  text ">" outside root element will be ignored.
```

**Comment by deepred5** [comment]
修改header.vue后，访问http://localhost:8888
控制台报错，无法加载
```
Uncaught (in promise) TypeError: Cannot create property 'type' on string '<html><frameset> <frame id='top' src="http://172.30.2.1/disable/disable.htm"><noframes> <body>Your browse does not support frame!</body> </noframes> </frameset> </html>'
```

**Comment by superman66** [comment]
有没有详细点的错误信息，或者贴出你改动的代码。仅靠这些好像难以判断错误的原因

**Comment by deepred5** [comment]
好像是网络问题，所以访问不到豆瓣api，现在可以了。不过你的header.vue好像有语法问题，多了个>，最好改下。

**Comment by superman66** [comment]
@deepred5 多谢提醒，已经更改了

**Comment by bxychy** [comment]
ERROR in %1 is not a valid Win32 application.
\\?\G:\My_object\vue-Example\vue2.x-douban\node_modules\node-sass\vendor\win32-x64-51\binding.node
 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-0b49e836!./~/sass-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue 4:14-240 13:2-17:4 14:20-246

运行报这个错误,没改任何代码刚拉下来。刚刚npm....

**Comment by deepred5** [comment]
node-sass可能没安装成功。可以使用cnpm下载看看。

**Comment by bxychy** [comment]
好的我试试
